name: maicon
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pip:
    - opencv-python
    - ultralytics
    - pillow
    - jupyter
    - fire